//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSTest.Checklas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsByBrandOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WSTest.Properties.Settings.Default.WSTest_Checklas_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetItemsByBrandCompletedEventHandler GetItemsByBrandCompleted;
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login() {
            object[] results = this.Invoke("Login", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync() {
            this.LoginAsync(null);
        }
        
        /// <remarks/>
        public void LoginAsync(object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[0], this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemsByBrand", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse GetItemsByBrand(string guid, string brand) {
            object[] results = this.Invoke("GetItemsByBrand", new object[] {
                        guid,
                        brand});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsByBrandAsync(string guid, string brand) {
            this.GetItemsByBrandAsync(guid, brand, null);
        }
        
        /// <remarks/>
        public void GetItemsByBrandAsync(string guid, string brand, object userState) {
            if ((this.GetItemsByBrandOperationCompleted == null)) {
                this.GetItemsByBrandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsByBrandOperationCompleted);
            }
            this.InvokeAsync("GetItemsByBrand", new object[] {
                        guid,
                        brand}, this.GetItemsByBrandOperationCompleted, userState);
        }
        
        private void OnGetItemsByBrandOperationCompleted(object arg) {
            if ((this.GetItemsByBrandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsByBrandCompleted(this, new GetItemsByBrandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse GetItems(string guid, Request[] itr) {
            object[] results = this.Invoke("GetItems", new object[] {
                        guid,
                        itr});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(string guid, Request[] itr) {
            this.GetItemsAsync(guid, itr, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(string guid, Request[] itr, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        guid,
                        itr}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemResponse {
        
        private bool responseflagField;
        
        private Item[] itemlistField;
        
        /// <remarks/>
        public bool responseflag {
            get {
                return this.responseflagField;
            }
            set {
                this.responseflagField = value;
            }
        }
        
        /// <remarks/>
        public Item[] itemlist {
            get {
                return this.itemlistField;
            }
            set {
                this.itemlistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Item {
        
        private string itemCodeField;
        
        private string itemNameField;
        
        private string itmsGrpCodField;
        
        private string itmsGrpNamField;
        
        private double priceField;
        
        private string u_kmpanyaField;
        
        private string u_ebatField;
        
        private string u_lastikTipiField;
        
        private string u_yukEndeksField;
        
        private string u_hizEndeksField;
        
        private string u_rftField;
        
        private string u_isaretlerField;
        
        private string u_oeField;
        
        private string u_oeMarkField;
        
        private string u_menseiField;
        
        private string u_yakitPerField;
        
        private string u_desibelField;
        
        private string u_islakZeminField;
        
        private string u_kullanimField;
        
        private string u_eMarkField;
        
        private string u_yayindaMiField;
        
        private string u_renkField;
        
        private string u_konsantreOraniField;
        
        private string u_aModelField;
        
        private string u_alasimField;
        
        private string u_tonajField;
        
        private string u_devirHiziField;
        
        private string u_amperField;
        
        private string u_xlField;
        
        private string u_mevsimField;
        
        private string u_basincField;
        
        private string u_portalField;
        
        private string u_eTicaretField;
        
        private string u_desenField;
        
        private string u_katalogField;
        
        private string u_markaField;
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItmsGrpCod {
            get {
                return this.itmsGrpCodField;
            }
            set {
                this.itmsGrpCodField = value;
            }
        }
        
        /// <remarks/>
        public string ItmsGrpNam {
            get {
                return this.itmsGrpNamField;
            }
            set {
                this.itmsGrpNamField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string U_kmpanya {
            get {
                return this.u_kmpanyaField;
            }
            set {
                this.u_kmpanyaField = value;
            }
        }
        
        /// <remarks/>
        public string U_ebat {
            get {
                return this.u_ebatField;
            }
            set {
                this.u_ebatField = value;
            }
        }
        
        /// <remarks/>
        public string U_lastikTipi {
            get {
                return this.u_lastikTipiField;
            }
            set {
                this.u_lastikTipiField = value;
            }
        }
        
        /// <remarks/>
        public string U_yukEndeks {
            get {
                return this.u_yukEndeksField;
            }
            set {
                this.u_yukEndeksField = value;
            }
        }
        
        /// <remarks/>
        public string U_hizEndeks {
            get {
                return this.u_hizEndeksField;
            }
            set {
                this.u_hizEndeksField = value;
            }
        }
        
        /// <remarks/>
        public string U_rft {
            get {
                return this.u_rftField;
            }
            set {
                this.u_rftField = value;
            }
        }
        
        /// <remarks/>
        public string U_isaretler {
            get {
                return this.u_isaretlerField;
            }
            set {
                this.u_isaretlerField = value;
            }
        }
        
        /// <remarks/>
        public string U_oe {
            get {
                return this.u_oeField;
            }
            set {
                this.u_oeField = value;
            }
        }
        
        /// <remarks/>
        public string U_oeMark {
            get {
                return this.u_oeMarkField;
            }
            set {
                this.u_oeMarkField = value;
            }
        }
        
        /// <remarks/>
        public string U_mensei {
            get {
                return this.u_menseiField;
            }
            set {
                this.u_menseiField = value;
            }
        }
        
        /// <remarks/>
        public string U_yakitPer {
            get {
                return this.u_yakitPerField;
            }
            set {
                this.u_yakitPerField = value;
            }
        }
        
        /// <remarks/>
        public string U_desibel {
            get {
                return this.u_desibelField;
            }
            set {
                this.u_desibelField = value;
            }
        }
        
        /// <remarks/>
        public string U_islakZemin {
            get {
                return this.u_islakZeminField;
            }
            set {
                this.u_islakZeminField = value;
            }
        }
        
        /// <remarks/>
        public string U_kullanim {
            get {
                return this.u_kullanimField;
            }
            set {
                this.u_kullanimField = value;
            }
        }
        
        /// <remarks/>
        public string U_eMark {
            get {
                return this.u_eMarkField;
            }
            set {
                this.u_eMarkField = value;
            }
        }
        
        /// <remarks/>
        public string U_yayindaMi {
            get {
                return this.u_yayindaMiField;
            }
            set {
                this.u_yayindaMiField = value;
            }
        }
        
        /// <remarks/>
        public string U_renk {
            get {
                return this.u_renkField;
            }
            set {
                this.u_renkField = value;
            }
        }
        
        /// <remarks/>
        public string U_konsantreOrani {
            get {
                return this.u_konsantreOraniField;
            }
            set {
                this.u_konsantreOraniField = value;
            }
        }
        
        /// <remarks/>
        public string U_aModel {
            get {
                return this.u_aModelField;
            }
            set {
                this.u_aModelField = value;
            }
        }
        
        /// <remarks/>
        public string U_alasim {
            get {
                return this.u_alasimField;
            }
            set {
                this.u_alasimField = value;
            }
        }
        
        /// <remarks/>
        public string U_tonaj {
            get {
                return this.u_tonajField;
            }
            set {
                this.u_tonajField = value;
            }
        }
        
        /// <remarks/>
        public string U_devirHizi {
            get {
                return this.u_devirHiziField;
            }
            set {
                this.u_devirHiziField = value;
            }
        }
        
        /// <remarks/>
        public string U_amper {
            get {
                return this.u_amperField;
            }
            set {
                this.u_amperField = value;
            }
        }
        
        /// <remarks/>
        public string U_xl {
            get {
                return this.u_xlField;
            }
            set {
                this.u_xlField = value;
            }
        }
        
        /// <remarks/>
        public string U_mevsim {
            get {
                return this.u_mevsimField;
            }
            set {
                this.u_mevsimField = value;
            }
        }
        
        /// <remarks/>
        public string U_basinc {
            get {
                return this.u_basincField;
            }
            set {
                this.u_basincField = value;
            }
        }
        
        /// <remarks/>
        public string U_portal {
            get {
                return this.u_portalField;
            }
            set {
                this.u_portalField = value;
            }
        }
        
        /// <remarks/>
        public string U_eTicaret {
            get {
                return this.u_eTicaretField;
            }
            set {
                this.u_eTicaretField = value;
            }
        }
        
        /// <remarks/>
        public string U_desen {
            get {
                return this.u_desenField;
            }
            set {
                this.u_desenField = value;
            }
        }
        
        /// <remarks/>
        public string U_katalog {
            get {
                return this.u_katalogField;
            }
            set {
                this.u_katalogField = value;
            }
        }
        
        /// <remarks/>
        public string U_marka {
            get {
                return this.u_markaField;
            }
            set {
                this.u_markaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Request {
        
        private string tableField;
        
        private string fieldField;
        
        private string conditionField;
        
        private string valueField;
        
        private string opField;
        
        /// <remarks/>
        public string Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string op {
            get {
                return this.opField;
            }
            set {
                this.opField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetItemsByBrandCompletedEventHandler(object sender, GetItemsByBrandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsByBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsByBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591